services:
  monitor:
    image: ghcr.io/005-bot/monitor:latest
    environment:
      - REDIS__URL=redis://redis:6379
      - REDIS__PREFIX=monitor
      - SCRAPER__URL=http://93.92.65.26/aspx/Gorod.htm
      - SCRAPER__INTERVAL=${SCRAPER__INTERVAL}
    networks:
      - internal
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 128M
      update_config:
        order: stop-first
        monitor: 5s
        failure_action: rollback
      rollback_config:
        order: stop-first
        monitor: 5s
   
networks:
  internal:
    external: true
